### ISSUE TITLE
Stream works - audio awful  :).

### ISSUE THREAD

**Issue by greghains** [kylejohnson/Patiobar#12]
Good afternoon.
I know the problem is most likely something I have done, as I found the first part of the tutorial work perfectly. I first heard the Pandora stream come through clearly through the headphones. After I got port 3000 working (thank you fellow contributors), I now hear the music, but not terribly loud and full of static. It does respond to changing tracks moth interface, so Im assuming its a Pi audio hardware config thing.  The sound card listed is a BCM2835 ALSA.
Is it something in one of my config files that's not working?
Any ideas please?
Greg

**Comment by bt1957** [comment]
Hello Greg,

Couple of questions:

Which version of the Pi do you have?
Do you have an an hdmi cable plugged in?

**Comment by greghains** [comment]
Hi there.

 

Thank you for responding – especially so quickly.

 

It’s the Model B.

Over the last half hour I have made more progress, putting in the boot config audio_pwm_mode=2 – which seems to help a little bit.

 

I did have HDMI plugged into it (I prefer headless anyway), as I read it could be noise from other cables/devices, but that didn’t help much.

If I wind the volume to the audio jack very low, less static is heard, and I’m hoping that as it is going into an aux port on a small amp, that there is enough line level for the amp to use.  I’ll know tomorrow when I plug it in.

 

Cheers, and thanks.

Greg

**Comment by bt1957** [comment]
Hello Greg...
Yeah for progress:-)
I have two small external USB DAC's that I have used, and both have sounded great.

I have not used the internal sound card on the Pi as I read that it is a weak spot (and I had these two USB DAC's sitting around, that I wanted to try).

I too, run headless, and use this command to adjust volume:

amixer set PCM -- 60%

Cheers and let me know how it goes.

**Comment by greghains** [comment]
Hi there,

 

OK then – I might look at that option.

May I ask which USB DACs you use please?

 

Thanks again.

**Comment by bt1957** [comment]
Hello again Greg...
Yes, one is the Y1 Lite, by "AMB Labs" which was a DIY project that I had built for me, some years ago.  It sounds really great, but the PCM volume control does not work with it.

The other one sounds great too, and is 100% plug and play, the PCM volume does work.  It s the NuForce uDAC2 (not the latest), it works perfectly and has it's own volume knob (which is handy for level matching for your amp).  This one is still available and is not expensive.

I used raspi-config to turn off the internal soundcard, which maybe helps too, in saving some CPU cycles.

Cheers!

**Comment by greghains** [comment]
Thank you – you’ve put me on the right track.  ☺

Good tip re the CPU cycles too!

**Comment by kylejohnson** [comment]
Hopefully you got the issue solved.  Closing this out as it isn't actually Patiobar related.  FWIW I usually use a USB DAC.

**Comment by greghains** [comment]
Hi Kyle.

 

Thanks for this – yes, all sorted.

 

Cheers,

Greg
