### ISSUE TITLE
(feature request) Post the songURL link somewhere on the patiobar page (or add some kind of replay functionality)

### ISSUE THREAD

**Issue by hatcreek68** [kylejohnson/Patiobar#17]
It would be nice to be able to click the link to hear the song again (or otherwise a way to replay the song).

**Comment by USAFPride** [comment]
See [this link](https://github.com/PromyLOPh/pianobar/issues/601) for replay as Patiobar is just an interface to pianobar

**Comment by kylejohnson** [comment]
Closing, as this requires support from pianobar.
