### ISSUE TITLE
Display station name

### ISSUE THREAD

**Issue by robcazzaro** [kylejohnson/Patiobar#18]
I might be missing something, but where can I see the station being played? My Patiobar/pianobar is used by two people listening to different stations. Would be good to be able to see which station is playing, in addition to the song being played

BTW: thanks for the awesome Patiobar!

**Comment by USAFPride** [comment]
Paitobar reads the information from the ~/.config/pianobar/currentSong file.  I see you asked your question over at the pianobar git, but your question should have been "how do I add the station name to the currentSong string?"  Once the station name is in the string, then Patiobar can parse it out and display it.

**Comment by robcazzaro** [comment]
Hello, as per the linked issue, it would be pretty easy to add the station name to the currentSong file (using the existing eventcmd.sh). I could try modifying it (the part that explicitly says "here be dragons! don't change anything below" :), but I'd like to know what format you would prefer to have, for Patiobar to parse it correctly

**Comment by USAFPride** [comment]
just add it to the end of this line:
`echo -n "${artist},,,${title},,,${album},,,${coverArt},,,${rating}" > "$currentSong"` (it looks like the query line above would also need a tweak)

Then you will need to update all the "display" files.  I see a couple options for showing the station:
1. different color for the station button
2. station name above the cover art
3. station name above the song title

**Comment by kylejohnson** [comment]
![image](https://user-images.githubusercontent.com/114193/41259581-5831da94-6d91-11e8-8952-b73002cfb57d.png)
As of commit 10caa90, the currently playing station will now be highlighted in green.
