### ISSUE TITLE
Auto refresh on Song Change

### ISSUE THREAD

**Issue by tracerrx** [kylejohnson/Patiobar#19]
I added the below to make the screen refresh upon a change in the nowplaying file (my filename differs from your CurrentSong file)

`var fs = require('fs');
var filePath = process.env.HOME + '/.config/pianobar/nowplaying';
var file = fs.readFileSync(filePath);
console.log('Initial File content: ' + file);

fs.watch(filePath, function(event, filename) {
          if(filename){
                      console.log('Event : ' + event);
                      console.log(filename + ' file Changed ...');
                      file = fs.readFileSync(filePath);
                      console.log('File content at : ' + new Date() + ' is \n' + file);
                      readCurrentSong();
                    }
          else{
                      console.log('filename not provided')
                    }
});`

**Comment by kylejohnson** [comment]
I'm not sure why this is necessary - the UI should automatically update the relevant elements (song title, album art, etc) when the song changes, without doing a full page refresh.  Is this not happening?

**Comment by tracerrx** [comment]
Was not working on chrome 67/macos until I made the changes
