### ISSUE TITLE
Control Pianobar via Patiobar http 

### ISSUE THREAD

**Issue by PhilipvonMaltzahn** [kylejohnson/Patiobar#23]
I have Patiobar up and running on a headless machine.

I'd like to build a button control interface using a program called Eventghost. I'm a novice here, bootstrapping a system and learning as I go. 

Is there a way to send commands to the Patiobar server via http Send request? I'm thinking something along the lines of : http://pandora:3000/?Pause or http://pandora:3000/?Station37

Thank you.

**Comment by kylejohnson** [comment]
Patiobar really isn't made for this, instead, you could directly interface with Pianobar's FIFO event command, which is what Patiobar talks to on the bendend.
