### ISSUE TITLE
thumbs up, thumbs down buttons end play

### ISSUE THREAD

**Issue by GeneDot3** [kylejohnson/Patiobar#29]
Not sure how active this project is at the time of this writing.
Love the package.  It runs great if I leave it alone, once I try to promote or ban (thumbs up/down) a song play stops and I have to issue pbstop and pbstart to begin play again. This is on a Raspberry pi 3b running Raspian (buster) OS over wifi connection. Song skip, song shelve, pause and vol up/down seem to work ok. 

Thanks in advance.

**Comment by kylejohnson** [comment]
Hmm!  I am seeing this issue too.  I'll take a look.

**Comment by GeneDot3** [comment]
Thanks!

    On Tuesday, March 2, 2021, 1:17:05 PM EST, Kyle Johnson <notifications@github.com> wrote:  
 
 


Hmm! I am seeing this issue too. I'll take a look.

**Comment by kylejohnson** [comment]
The push should be fixed / at least, it is now working on my end.

**Comment by GeneDot3** [comment]
Not that savvy with github, will an update/upgrade to Raspian apply the fix?

**Comment by kylejohnson** [comment]
Sorry, I'm not sure how Raspbian bundles Patiobar.
Did you install it yourself, or was it included when you installed Raspbian?

**Comment by GeneDot3** [comment]
Not bundled, I installed it from myself.

    On Friday, March 5, 2021, 9:53:28 AM EST, Kyle Johnson <notifications@github.com> wrote:  
 
 


Sorry, I'm not sure how Raspbian bundles Patiobar.
Did you install it yourself, or was it included when you installed Raspbian?
