### ISSUE TITLE
Album Art & Hamburger, Etc

### ISSUE THREAD

**Issue by wellmans** [kylejohnson/Patiobar#30]
It's working but I don't see album art and the hamburger control doesn't do anything. I've googled but can't find this exact issue.

**Comment by kylejohnson** [comment]
Sorry for the delayed response.
Are you still having this issue?  If so,

* How did you install Patiobar?
* Please post screenshots of your issue
* If possible, also post output from your web browser's Inspector
* Please post the output from `cd Patiobar && node index.js`
