### ISSUE TITLE
Web Interface not interacting

### ISSUE THREAD

**Issue by K37V1N** [kylejohnson/Patiobar#31]
I'm getting this error message when I have it setup on my Raspberry Pi. The web-interface loads but the buttons don't work:
pi@Pandora-Pi:~ $ cd Patiobar && node index.js
a user connected
internal/fs/utils.js:314
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/pi/.config/pianobar/currentSong'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at readCurrentSong (/home/pi/Patiobar/index.js:16:23)
    at Namespace.<anonymous> (/home/pi/Patiobar/index.js:65:2)
    at Namespace.emit (events.js:375:28)
    at Namespace.emit (/home/pi/Patiobar/node_modules/socket.io/lib/namespace.js:213:10)
    at /home/pi/Patiobar/node_modules/socket.io/lib/namespace.js:181:14
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/pi/.config/pianobar/currentSong'

**Comment by kylejohnson** [comment]
Do you have Pianobar running?  Patiobar is yelling that it can't find the current song.  Can you also post our Pianobar config?

**Comment by K37V1N** [comment]
Yes, Pianobar is running currently in another terminal window.
~/.config/pianobar/config:
![Pianobar-Output](https://user-images.githubusercontent.com/31780583/125959065-8a6ce34f-c7b1-4805-9573-2d720a6a8f55.PNG)


# This is an example configuration file for pianobar. You may remove the # from
# lines you need and copy/move this file to ~/.config/pianobar/config
# See manpage for a description of the config keys
#
# User
user = ********@gmail.com
password = *********
# or
#password_command = gpg --decrypt ~/password

# Proxy (for those who are not living in the USA)
#control_proxy = http://127.0.0.1:9090/

# Keybindings
act_help = ?
act_songlove = +
act_songban = -
act_stationaddmusic = a
act_stationcreate = c
act_stationdelete = d
act_songexplain = e
act_stationaddbygenre = g
act_songinfo = i
act_addshared = j
act_songmove = m
act_songnext = n
act_songpause = p
act_quit = q
act_stationrename = r
act_stationchange = s
act_songtired = t
act_upcoming = u
act_stationselectquickmix = x
act_voldown = (
act_volup = )

# Misc
#audio_quality = low
autostart_station = 344454569046454719

#event_command = /home/pi/.config/pianobar/scripts/eventcmd.sh
fifo = /home/pi/Patiobar/ctl
#sort = quickmix_10_name_az
#love_icon = [+]
#ban_icon = [-]
volume = 0

# Format strings
format_nowplaying_song = SONG: %t | %a | %l
format_nowplaying_station = STATION: %n | %i
format_msg_time = TIME: %s
# No special prefix on songs, stations or info
format_msg_nowplaying = %s
format_msg_info = %s

# high-quality audio (192k mp3, for Pandora One subscribers only!)
#audio_quality = high
#rpc_host = internal-tuner.pandora.com
#partner_user = pandora one
#partner_password = TVCKIBGS9AO9TSYLNNFUML0743LH82D
#device = D01
#encrypt_password = 2%3WCL*JU$MP]4
#decrypt_password = U#IO$RZPAB%VX2

tls_fingerprint = 2D0AFDAFA16F4B5C0A43F3CB1D4752F9535507C0

**Comment by kylejohnson** [comment]
Looks like the issue is most likely that the `event_command` is not configured in you pianobar config file. `event_command` should point to the location on disk of `eventcmd.sh` from this repo, e.g. `event_command = /home/pi/Patiobar/eventcmd.sh`

How did you install patiobar?  Did you run the install command?

**Comment by K37V1N** [comment]
I installed using this:

git clone https://github.com/kylejohnson/Patiobar.git
cd Patiobar
bash install.sh

I'll see if I can make that change and let you know.

**Comment by K37V1N** [comment]
Confirmed this worked for me. I went into ~/.config/pianobar/config and removed the # from the event_command line, then changed it to:
event_command = /home/pi/Patiobar/eventcmd.sh

This fixed the issue perfectly. Thanks for all of your help!
