### ISSUE TITLE
Prereqs?

### ISSUE THREAD

**Issue by mwheinz** [kylejohnson/Patiobar#6]
Your installer doesn't check for missing pre-requisites and I apparently don't have "npm" installed. What do I need to have installed to try this?

**Comment by bt1957** [comment]
Hello mwheinz, I had the same problem.  You can install npm with the terminal command (I am using a Raspberry Pi 3 w/Raspian OS):

sudo apt-get install npm

After npm gets installed, go to the Patiobar directory in terminal and try the command

node index.js

It will probably error, and you then need to install more software with npm via the terminal.  For me, it was:

sudo npm install express

then:

sudo npm install socket.io

After that, it worked (I had to browse to the actual RasPi's IP address: 192.168.1.xxx:3000 instead of the 172.0.0.1:3000 that is shown pbstart script).

Also looked at "thedavej"'s auto start instructions, followed his lead, and got that working too.

Very pleased with this setup!

Cheers!

**Comment by mwheinz** [comment]
Thanks, but when I try to run it I still get:

pi@raspberrypi ~/work/Patiobar $ node index.js 
-bash: node: command not found

The problem is that apt search reveals literally hundreds of packages that call themselves "node-*" - I can't tell which one(s) I need.

**Comment by bt1957** [comment]
Here is my node version:

 $ apt list node
node/stable 0.3.2-7.4 all

I wonder if you have multiple version of node installed?

You might try these commands:

sudo apt-get update
then
sudo apt-get upgrade

To get the latest softwares.

**Comment by mwheinz** [comment]
Looks like I've got it working completely now, as long as I use "nodejs". Interestingly, "node" doesn't seem to have anything to do with node js:

978     node/stable 0.3.2-7.4 all
      1   Amateur Packet Radio Node program (transitional package)

**Comment by bt1957** [comment]
Glad to hear it is working, mw!

Here is a little python script I have in my path on my Pandora-Pi...when I am in via SSH and pianobar is running, I can run this and it shows the song, artist, album and a link to the cover art (you can Right Click->Open Link, and see the art:
(might need to edit the path to your pianobar config directory):


=============================
# showsong.py
# USAGE: python showsong.py
# make an alias in your .bashrc for easy access :-)
#
filename = open("/home/pi/.config/pianobar/currentSong","r")  #edit your path if needed
mysongs = filename.read().split(',,,')
# print green text:
print '\x1b[1;32;40m'
print " "
#
print "Song   : " + mysongs[1]
print('\x1b[1;33;40m' + 'Artist : ' + mysongs[0])
print('\x1b[1;34;40m' + 'Album  : ' + mysongs[2])
print('\x1b[1;37;40m' + 'Art    : ' + '\x1b[4;36;40m' + mysongs[3])
#
print " "
print '\x1b[0m'    #reset term colors
#
=============================

Cheers!

**Comment by bt1957** [comment]
Here is a little python script that will display the song, artist, album and provide a link to the album art.
I use it when I an in via SSH on the Pi where pianobar is running (put in in your path and make a .bashrc alias to the command, for quick access):

`=============================
# showsong.py
# USAGE: python showsong.py
# make an alias in your .bashrc for easy access :-)
# Edit path to your "currentSong" file if needed.
#
filename = open("/home/pi/.config/pianobar/currentSong","r")  #edit your path if needed
mysongs = filename.read().split(',,,')
# print green text:
print '\x1b[1;32;40m'
print " "
#
print "Song   : " + mysongs[1]
print('\x1b[1;33;40m' + 'Artist : ' + mysongs[0])
print('\x1b[1;34;40m' + 'Album  : ' + mysongs[2])
print('\x1b[1;37;40m' + 'Art    : ' + '\x1b[4;36;40m' + mysongs[3])
#
print " "
print '\x1b[0m'    #reset term colors
#
=============================
`
