### ISSUE TITLE
Skip button starts a loop

### ISSUE THREAD

**Issue by John-F-R** [kylejohnson/Patiobar#8]
when you press the skip button in the music tab, it skips songs in a loop until you press pause

**Comment by kylejohnson** [comment]
I don't see this issue at all.  By the `skip` button, do you mean the `next` button, which is to the right of the `play / pause` button?

**Comment by John-F-R** [comment]
To be completely honest I'm not even sure this was a project that I
abandoned almost a year ago I think the hardware I was trying to use was
just not right for the job
